name: Update language graph

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-language-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update language graph
        uses: cicirello/languages@v1
